### ISSUE TITLE
Fix Warnings old Packages - Bower/NPM

### ISSUE THREAD

**Issue by stuartshay** [stuartshay/NavigatorAuthentication.Web#180]
Fix Packages and Warnings 

![warnings](https://cloud.githubusercontent.com/assets/887805/14551949/487c5504-02a7-11e6-83ec-37fec22d1a25.PNG)

![warnings1](https://cloud.githubusercontent.com/assets/887805/14551954/52fd6644-02a7-11e6-8987-3de66d6c804a.PNG)

**Comment by leduong** [comment]
HI @stuartshay 

This issue can't resolved
